apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weather-svc
  labels:
    app: weather-svc
    version: v1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: weather-svc
        version: v1
    spec:
      containers:
        - image: pj3677/weather-svc:1.0.0
          imagePullPolicy: Always
          name: svc
          args:
            [
              "--port",
              "$(PORT)",
              "--temperatureSvcURL",
              "$(TEMPERATURE_SVC)",
              "--citySvcURL",
              "$(CITY_SVC)",
            ]
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: TEMPERATURE_SVC
              value: "http://temperature-svc"
            - name: CITY_SVC
              value: "http://city-svc"
---
kind: Service
apiVersion: v1
metadata:
  name: weather-svc
  labels:
    app: weather-svc
spec:
  selector:
    app: weather-svc
  ports:
    - port: 80
      name: http
      targetPort: 8080
